### ISSUE TITLE
tm1650 will no longer compile

### ISSUE THREAD

**Issue by pingel20** [trip5/EspHome-Led-Clock#1]
Hi Mr. trip5,

Your tm1650 component will not compile with the latest Esphome.
There seems to be a breaking change regarding the display component.
See:
https://github.com/landonr/lilygo-tdisplays3-esphome/pull/46

It looks like you have to remove following line from 'display.py':

 await cg.register_component(var, config)

https://community.home-assistant.io/t/st7789-external-display-component-wont-build-since-end-of-2023-esphome-version/682506

Can you please fix this?

Thank you.

**Comment by trip5** [comment]
It's already been fixed upstream.  I must have missed it in my feed to sync the fork.  Thanks for pointing it out.
