### ISSUE TITLE
Problem when ota update via web browser 

### ISSUE THREAD

**Issue by tungtran-user** [trip5/EspHome-Led-Clock#4]
Hello, i have problem when ota update via web browser:
Update Failed: ERROR[10]: Magic byte is not 0xE9
I'm using 303wifilc01

**Comment by trip5** [comment]
Let's start basic.  You're sure you're building with ESPHome?  Or are you trying to upload a YAML file?

When building with ESPHome, you need to use the OTA update binary.

**Comment by tungtran-user** [comment]
I did install esphome on the esp, then upload yaml file

**Comment by trip5** [comment]
You can't upload the YAML directly to the device.  You need to run ESPHome on a computer, build a binary using the YAML.

Try following this step-by-step to get Docker onto your computer: https://deploy-preview-4411--esphome.netlify.app/guides/beginners_guide_docker_desktop

And this to compile the YAML: https://deploy-preview-4411--esphome.netlify.app/guides/beginners_guide_adding_devices

And if you find it helpful, leave a comment under here? https://github.com/esphome/esphome-docs/pull/4411

**Comment by tungtran-user** [comment]
I upload .bin file, it show "update successful!", but nothing show on the clock

**Comment by trip5** [comment]
If you want help, I will need more information.  One sentence at a time is not giving me enough information to help you.

Please tell me your entire process up until now.  There is something you are doing wrong and I can't guess what it is.

**Comment by tungtran-user** [comment]
Thank for your help! Problem solved. I successfully upload bin file using nodemcu firmware flasher tool.
